kind: Service
apiVersion: v1
metadata:
  name: category-api
spec:
  selector:
    app: category-api
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-api
  labels:
    app: category-api
spec:
  selector:
    matchLabels:
      app: category-api
  replicas: 1
  template:
    metadata:
      labels:
        app: category-api
    spec:
      containers:
        - name: category-api
          image: evato/category-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  defaultBackend:
    service:
      name: category-api
      port:
        number: 9091
  rules:
    - host: ingress.demo
      http:
        paths:
          - path: /categories
            pathType: Prefix
            backend:
              service:
                name: category-api
                port:
                  number: 9091
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: category-api
#                port:
#                  number: 9091
